export { default as SideProjectSection } from './deprecated/side-project'
export { default as MainPage } from './main'
export { default as WorkSection } from './deprecated/work'
export { default as ProjectPage } from './project.js'
export { default as LockedPage } from '../pages/locked'
